
DROP DATABASE IF EXISTS CriteriaDB;
CREATE DATABASE CriteriaDB;

USE CriteriaDB;


CREATE USER IF NOT EXISTS 'appuser'@'localhost' IDENTIFIED BY 'appuser123!ABChello9045';
GRANT ALL PRIVILEGES ON CriteriaDB.* TO 'appuser'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE Criterion(
	Id int NOT NULL AUTO_INCREMENT,
	Type VARCHAR(10),
	CriterionText VARCHAR(100),
	StudyId VARCHAR(50),
	Filename VARCHAR(40),
	CONSTRAINT Criterion PRIMARY KEY (Id)
);

SHOW WARNINGS;
