
DROP DATABASE IF EXISTS CriteriaDB;
CREATE DATABASE CriteriaDB;

USE CriteriaDB;

CREATE TABLE Criterion(
	Id int NOT NULL AUTO_INCREMENT,
	Type VARCHAR(10),
	CriterionText VARCHAR(100),
	StudyId VARCHAR(50),
	CONSTRAINT Criterion PRIMARY KEY (Id)
);

SHOW WARNINGS;
